# Import the relevant libraries

In [1]:
import numpy as np

## Creating a tensor

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
t = np.array([m1,m2])

In [5]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

## Checking its shape

In [6]:
t.shape

(2, 2, 3)

## Manually creating a tensor

In [7]:
t_manual = np.array([[[ 5, 12,  6], [-3,  0, 14]], [[ 9,  8,  7], [ 1,  3, -5]]])

In [8]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [9]:
m1 = np.array([[1,3,5],[4,6,9]])
m1

array([[1, 3, 5],
       [4, 6, 9]])

In [10]:
m2 = np.array([[5,3,7],[8,2,3]])
m2

array([[5, 3, 7],
       [8, 2, 3]])

In [11]:
m3 = np.array([m1,m2, m2])
m3

array([[[1, 3, 5],
        [4, 6, 9]],

       [[5, 3, 7],
        [8, 2, 3]],

       [[5, 3, 7],
        [8, 2, 3]]])

In [12]:
m3.shape

(3, 2, 3)

In [13]:
m_sum = m1+m2
m_sum

array([[ 6,  6, 12],
       [12,  8, 12]])

In [14]:
m1+m3

array([[[ 2,  6, 10],
        [ 8, 12, 18]],

       [[ 6,  6, 12],
        [12,  8, 12]],

       [[ 6,  6, 12],
        [12,  8, 12]]])

In [15]:
m1+3

array([[ 4,  6,  8],
       [ 7,  9, 12]])

In [16]:
m4 = np.array([[1,3],[4,6]])
m1+m4

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
m1.T

In [ ]:
m3

In [ ]:
m3.T

In [ ]:
v = np.array([3,6,9])
v.T

In [ ]:
print(m1)
print(m2)
m1*m2

In [ ]:
np.dot(m1, m2.T)

In [24]:
v1 = np.array([[3,5,7]])
v2 = np.array([4,2,3])
d = np.dot(v1,3)
d

array([[ 9, 15, 21]])

In [25]:
v3 = np.array([[2],[3],[4]])
m3_3 = np.dot(v3,v1)
m3_3

array([[ 6, 10, 14],
       [ 9, 15, 21],
       [12, 20, 28]])